### ISSUE TITLE
How to handle app crashes

### ISSUE THREAD

**Issue by Inversion-NL** [fabianblom/Toon-Android#11]
Find an sollution on how to handle app crashes.

When the app is in the Play Store, app crashes are automatically send.
However these reports are very limited.

My suggestion would be Firebase Crashlytics:
https://firebase.google.com/docs/crashlytics/

**Comment by WickedMaster** [comment]
This can be solved by publishing the app to the Play Store.

**Comment by Inversion-NL** [comment]
App published to Play Store and receiving crash reports: solved.
