### ISSUE TITLE
Add powerproduction to powerusage

### ISSUE THREAD

**Issue by glsf91** [fabianblom/Toon-Android#12]
When using /happ_pwrusage?action=GetCurrentUsage
{"result":"ok",
"powerUsage": {"value":276, "avgValue":373.76},
"powerProduction": {"value":0, "avgValue":0.00},
"gasUsage": {"value":0, "avgValue":0.00}
}
 for powerusage (field powerUsage), can you show also powerProduction into the PowerUsage but with minus sign.
If powerProduction > 0 then powerUsage will be 0. Same other way around.

Of course it will be better to change the text "Power usage" to "Power production" when displaying powerProduction.

**Comment by Inversion-NL** [comment]
Looks possible

**Comment by Inversion-NL** [comment]
Migrated to new issues repo here:
https://github.com/Inversion-NL/Toon-Android/issues/9
