### ISSUE TITLE
Build in auto-refresh

### ISSUE THREAD

**Issue by WickedMaster** [fabianblom/Toon-Android#27]
Since there is no auto-refresh yet, maybe it's an option to build in auto-refresh like in the webapplication now.

**Comment by Inversion-NL** [comment]
That's certainly possible. I was thinking about integrating the 'pull-to-refresh' (as an complementary to the refresh button in the toolbar) to the app:
https://developer.android.com/training/swipe/add-swipe-interface 
This library also provides feedback to the user in the familiar rotating icon on the top of the screen (below the toolbar).

**Comment by Inversion-NL** [comment]
And there should/could be an setting in the app to set the refresh to either disabled, 5s, 15s, 30s and 60s?

**Comment by WickedMaster** [comment]
Pull-to-refresh is a musthave. 5s refresh is good enough I think. No additional setting is needed (like in the official app).
