### ISSUE TITLE
As of firmware 4.15.6 Toon supports multiple meters

### ISSUE THREAD

**Issue by Inversion-NL** [fabianblom/Toon-Android#3]
This could become an issue later on.
More information here:
https://forum.toon.nl/software-updates-26/software-update-4-15-6-1978#post28089

**Comment by fabianblom** [comment]
Thanks for mentioning. It's something we should keep an eye on I guess.
I'm still using an old firmware version and my Toon will not be updated anymore.
We can however build it in when someone requests it if you like? I won't think it will take that much work.

I should set up Android Studio again. :) I recently reinstalled my computer.

**Comment by Inversion-NL** [comment]
As soon as I get my Toon up and running again (got my filesystem messed recently) I'll see if I can find another sensor to pair.
You definitely set up Android studio again: a lot has changed (or will be in the near future) since Google I/O last week.

**Comment by Inversion-NL** [comment]
Not an issue anymore since another url is used to get the datat
