### ISSUE TITLE
Program info time not correct

### ISSUE THREAD

**Issue by TerrorSource** [fabianblom/Toon-Android#31]
Right upper corner, it shows "om 01:00 uur \n op"
There's no program set up in the settings of the screen so that should be the issue. Maybe it's better to show "no program set up" message or some kind.

![ToonAndroid](https://user-images.githubusercontent.com/20524866/55776961-aa4cc000-5a9e-11e9-83e5-8e114c8110bf.jpeg)

**Comment by Inversion-NL** [comment]
Solved in 0.5.4 (which is currently in Internal test)
