### ISSUE TITLE
Increase temperature first time 5 degrees

### ISSUE THREAD

**Issue by glsf91** [fabianblom/Toon-Android#33]
When starting 0.5.6 for the first time, the +/- increase/decrease the temperature with 5 degrees.
After setting default temp change settings it is working fine.

I think it is better to set the default setting to 1 or 0.5 degrees right away after install and setting is never set before.

**Comment by Inversion-NL** [comment]
I was unable to reproduce this bug.
Could you try and delete the app settings and try again?

**Comment by glsf91** [comment]
I tried again after delete app settings. Now the default setting is indeed 0.5 degrees.
Maybe something to do with the previous version I installed. Believe it was 0.5.2 (the first apk you published on github and mentioned on the Toon forum).

**Comment by Inversion-NL** [comment]
My thoughts exactly

**Comment by Inversion-NL** [comment]
Thanks for helping!
