### ISSUE TITLE
"stroom nu" not working

### ISSUE THREAD

**Issue by Inversion-NL** [fabianblom/Toon-Android#8]
"stroom nu" not working. It's stays zero.

More info:
https://www.domoticaforum.eu/viewtopic.php?f=102&t=11832&p=90411#p90390

**Comment by Inversion-NL** [comment]
That "zero" issue can be solved easily by just fetching the information from /happ_pwrusage?action=GetCurrentUsage. This keeps a track of the current usage.

{"result":"ok",
"powerUsage": {"value":276, "avgValue":373.76},
"powerProduction": {"value":0, "avgValue":0.00},
"gasUsage": {"value":0, "avgValue":0.00}
}

More info:
https://www.domoticaforum.eu/viewtopic.php?f=102&t=11832&p=90411#p90408

**Comment by WickedMaster** [comment]
I recommend to fetch the Gas Usage also from this same page so you can get rid of the meteradapter issue. That can differ when someone is using more than one meteradapter.

**Comment by glsf91** [comment]
Maybe you can show also powerProduction into the PowerUsage but with minus sign.
If powerProduction > 0 then powerUsage will be 0. Same other way around.

**Comment by Inversion-NL** [comment]
Could you create an separate request for that, please.
Otherwise it'll probably get lost in here.
Thanks
